# Generated by Django 3.1 on 2020-12-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='PairCompleteDate',
        ),
        migrations.AddField(
            model_name='member',
            name='boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='leftId',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='mid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='parentId',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='rightId',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
