# Generated by Django 3.1 on 2020-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20201230_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='leftId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='parentId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='payOut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='rightId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
