# Generated by Django 3.1 on 2020-12-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.member')),
            ],
        ),
    ]
