# Generated by Django 3.1 on 2021-01-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='boostedDays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='normalDays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
