# Generated by Django 3.1 on 2021-01-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20210107_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='gleftId',
            new_name='gleftleftId',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='grightId',
            new_name='gleftrightId',
        ),
        migrations.AddField(
            model_name='member',
            name='grightleftId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='grightrightId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
