# Generated by Django 3.1 on 2021-01-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20210108_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='userName',
            field=models.CharField(default='Sample', max_length=50, unique=True),
        ),
    ]
