# Generated by Django 3.1 on 2021-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='maching',
            field=models.BooleanField(default=False),
        ),
    ]
