# Generated by Django 3.1 on 2021-01-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20210117_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='accountNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='bankName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='ifscCode',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
