# Generated by Django 3.1 on 2021-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_auto_20210124_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='adjustBinary',
            field=models.BooleanField(default=False),
        ),
    ]
