# Generated by Django 3.1 on 2021-01-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_member_adjustbinary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
    ]
